services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    expose:
      - 23020
    restart: unless-stopped
    networks:
      - xyz-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - xyz-network

networks:
  xyz-network:
    driver: bridge